# Generated by Django 3.2.25 on 2025-09-16 15:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('login_token', models.CharField(blank=True, max_length=6, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('HIM', 'Health Information Management Officer'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('PHARMACY', 'Pharmacy')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CaseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_case_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=20)),
                ('pulse', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('urine_albumin', models.CharField(max_length=20)),
                ('urine_sugar', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='app.casefolder')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('user_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.casefolder')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('matric_no', models.CharField(max_length=15)),
                ('jamb_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('xray_no', models.CharField(max_length=15)),
                ('religion', models.CharField(choices=[('CHRISTIAN', 'Christianity'), ('MUSLIM', 'Muslim'), ('OTHER', 'Other')], max_length=25)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('Tribe', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.BooleanField(default=False)),
                ('measles', models.BooleanField(default=False)),
                ('chicken_pox', models.BooleanField(default=False)),
                ('tb', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('yellow_fever', models.BooleanField(default=False)),
                ('sti', models.BooleanField(default=False)),
                ('kidney_disease', models.BooleanField(default=False)),
                ('liver_disease', models.BooleanField(default=False)),
                ('epilepsy', models.BooleanField(default=False)),
                ('sc_disease', models.BooleanField(default=False)),
                ('gd_ulcer', models.BooleanField(default=False)),
                ('rta_injury', models.BooleanField(default=False)),
                ('alcohol_smoking', models.BooleanField(default=False)),
                ('previous_ops', models.BooleanField(default=False)),
                ('schistosomiasis', models.BooleanField(default=False)),
                ('respiratory_disease', models.BooleanField(default=False)),
                ('mental_disease', models.BooleanField(default=False)),
                ('hiv', models.BooleanField(default=False)),
                ('allergies', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='app.casefolder')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_medicalhistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('diagnosis', models.TextField()),
                ('date_of_admission', models.DateTimeField()),
                ('date_of_discharge', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='app.casefolder')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='casefolder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_folders', to='app.patient'),
        ),
    ]
